#message("CMAKE_CURRENT_LIST_DIR=" ${CMAKE_CURRENT_LIST_DIR})
#message("CMAKE_CURRENT_SOURCE_DIR=" ${CMAKE_CURRENT_SOURCE_DIR})
#message("CMAKE_CURRENT_DIR=" ${CMAKE_CURRENT_DIR})
#message("CMAKE_DIRECTORY_LABELS=" ${CMAKE_DIRECTORY_LABELS})
#message("CMAKE_HOME_DIRECTORY=" ${CMAKE_HOME_DIRECTORY})

ExternalProject_Add(googletest
    GIT_REPOSITORY git@github.com:google/googletest.git
    GIT_TAG release-1.10.0
    DOWNLOAD_NO_PROGRESS 0
    #PREFIX ${GTEST_PREFIX}
    UPDATE_COMMAND ""
    CONFIGURE_COMMAND ${CMAKE_COMMAND} -D CMAKE_C_COMPILER=${CMAKE_C_COMPILER} -D CMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER} -D CMAKE_BUILD_TYPE=Release  -DCMAKE_INSTALL_PREFIX=${EXTERNAL_ROOT} ../googletest 
    #CONFIGURE_COMMAND ${CMAKE_COMMAND} -D CMAKE_C_COMPILER=${CMAKE_C_COMPILER} -D CMAKE_BUILD_TYPE=Release  -DCMAKE_INSTALL_PREFIX=${EXTERNAL_ROOT} ../googletest 
    BUILD_COMMAND  ${CMAKE_COMMAND} --build . --config ${CMAKE_BUILD_TYPE}
    INSTALL_COMMAND  ${CMAKE_COMMAND} --build . --config ${CMAKE_BUILD_TYPE} --target install
)